AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'bin/pg_export'
  ExcludedMethods: ['describe', 'context']

Layout/LineLength:
  Max: 140

Style/ParallelAssignment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 30

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30
