AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Layout/LineLength:
  Max: 140

Style/ParallelAssignment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 30

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'lib/pg_export/configuration_parser.rb'
    - 'lib/pg_export/configuration.rb'

Metrics/PerceivedComplexity:
  Max: 30

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Layout/ExtraSpacing:
  Exclude:
    - 'lib/pg_export/configuration_parser.rb'

Metrics/ParameterLists:
  Exclude:
    - 'lib/pg_export/configuration.rb'

Metrics/ParameterLists:
  Enabled: false

Style/Semicolon:
  Enabled: false
